api: avoid compiler -Werror=return-type failures
Seen with gcc-7-2.9:
/usr/bin/cc -Dtcmu_EXPORTS -I/usr/include/libnl3 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/abuild/rpmbuild/BUILD/tcmu-runner-1.3.0/ccan  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Werror -Wall -Wdeclaration-after-statement -std=c99 -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/tcmu.dir/api.c.o   -c /home/abuild/rpmbuild/BUILD/tcmu-runner-1.3.0/api.c
[   15s] /home/abuild/rpmbuild/BUILD/tcmu-runner-1.3.0/api.c: In function 'tcmu_get_lba':
[   15s] /home/abuild/rpmbuild/BUILD/tcmu-runner-1.3.0/api.c:87:1: error: control reaches end of non-void function [-Werror=return-type]
...

Signed-off-by: David Disseldorp <ddiss@suse.de>